# Basic
title: 杨力的反思之旅
subtitle: 起个大早，赶个晚集。虽然是迟来了，但我也来啦^_^
welcome_message: Believe in yourself.
description: 嗨，我是杨力(Link Yang)，沉浸于iOS移动App，.Net企业应用等技术，Cocos2d系列/SmartFoxServer相关游戏技术的全能型创意工程师。
#creator: <a href="http://onev.cat">@onevcat</a>

#url: "http://mobileyangli.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: plain
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: green

blog_button:
    title: 博客
    description: 访问博客

#nav:
#    - {title: 项目, description: 我的项目, url: 'http://project.onevcat.com'}
#    - {title: 关于, description: 了解更多关于我, url: 'http://about.onevcat.com/'}
#    - {title: 订阅, description: 邮件订阅本站, url: '//store.objccn.io/subscribe'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
#comment:
#   disqus: onevcat
    # duoshuo:
#Social
#social:
#    weibo: onevcat
#    github: onevcat
#    twitter: onevcat
#    gplus: 107108267983477358170
#    mail: onev@onevcat.com

#Google Analytics
#ga:
#    id: UA-25719337-1
#    host: onevcat.com
